### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by theprototype** [ceandrade/brkga_combinatorial_auctions#1]
While running the makefile using "make all". I got the following error.

> In file included from cplex/branch_callback.cpp:35:0:
./include/branch_callback.hpp:33:30: fatal error: ilcplex/ilocplex.h: No such file or directory
compilation terminated.

There is no folder with name **ilcplex** in the source code

**Comment by ceandrade** [comment]
It is not an issue. This means that the dependence IBM ILOG CPLEX is missing. Since CPLEX is a proprietary package, it is not distributed in this repo. You must install IBM ILOG CPLEX in a location you prefer, and then change the Makefile (lines 93-99) according to your CPLEX installation. All this is described in the README.md

**Comment by theprototype** [comment]
Sorry. I have installed but given path incorrectly. Thank you for the reply
